### ISSUE TITLE
Single Frame selection throws an exception

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#1095]
__How to reproduce:__

  1. Open the "Android Systrace" sample trace in Trace Viewer.
  2. Expand one of the <tt>android.*</tt> tracks if necessary.
  2. Click on a single Frame.

__Expected behavior:__

The analysis view should show the details of the selected Frame.

__Actual behavior:__

The analysis view is blank and the following exception is thrown:

```
Uncaught TypeError: this.analysisViewRelatedEvents_.contains is not a function
    (anonymous function)                               @ brushing_state.html:140
    Model.iterateAllEventsInThisContainer              @ model.html:166
    (anonymous function)                               @ event_container.html:89
    visit                                              @ event_container.html:100
    EventContainer.iterateAllEventContainers           @ event_container.html:103
    EventContainer.iterateAllEvents                    @ event_container.html:88
    BrushingState.applyToModelSelectionState           @ brushing_state.html:134
    currentBrushingState                               @ selection_controller.html:161
    SelectionController.changeSelectionFromTimeline    @ selection_controller.html:225
    Polymer.onEndSelection_                            @ timeline_track_view.html:1015
    Polymer.onMouseUp_                                 @ mouse_mode_selector.html:369
    cleanupAndDispatchToMouseUp                        @ mouse_tracker.html:101
```

Moreover, all further selections also result in an empty analysis view (even if they don't contain any Frames) and throw the above exceptions as well.

**Comment by petrcermak** [comment]
I bisected the issue and it was caused in 2e3e248.

**Comment by petrcermak** [comment]
This should now be **fixed**.
